version: '3'
services:
  
  thalamus-sso:
    build:
      context: ../workspace/thalamus-sso
      dockerfile: Dockerfile
    container_name: thalamus-sso
    restart: unless-stopped
    ports:
      - "8199:80"
    volumes:
      - ../workspace/thalamus-sso:/var/www/html/
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_DEBUG: true
    env_file:
      - ../workspace/thalamus-sso/.env.local
    working_dir: /var/www/html/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - db
    networks:
      - app-network

  thalamus-backend:
    build:
      context: ../workspace/thalamus-backend-laravel
      dockerfile: Dockerfile
    container_name: thalamus-backend
    restart: unless-stopped
    ports:
      - "8110:80"
    volumes:
      - ../workspace/thalamus-backend-laravel:/var/www/html/
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_DEBUG: true
    env_file:
      - ../workspace/thalamus-backend-laravel/.env.local
    working_dir: /var/www/html/
    links:
      - db
    networks:
      - app-network

  thalamus-portal-frontend:
    build:
      context: ../workspace/thalamus-portal-frontend
      dockerfile: Dockerfile
      args:
        AMBIENTE: development
    container_name: thalamus-portal-frontend
    restart: unless-stopped
    ports:
      - "8107:80"
    environment:
      NODE_ENV: staging
    working_dir: /app
    networks:
      - app-network

  thalamus-indicadores-frontend:
    build:
      context: ../workspace/thalamus-indicador-frontend-vue3
      dockerfile: Dockerfile
      args:
        AMBIENTE: development
    container_name: thalamus-indicadores-frontend
    restart: unless-stopped
    ports:
      - "8101:80"
    environment:
      NODE_ENV: development
    working_dir: /app
    networks:
      - app-network

  thalamus-monitoramento-frontend:
    build:
      context: ../workspace/thalamus-monitoramento-frontend-vue3
      dockerfile: Dockerfile
      args:
        AMBIENTE: development
    container_name: thalamus-monitoramento-frontend
    restart: unless-stopped
    ports:
      - "8102:80"
    working_dir: /app
    networks:
      - app-network
  
  thalamus-acesso-frontend:
    build:
      context: ../workspace/thalamus-acesso-frontend-vue3
      dockerfile: Dockerfile
      args:
        AMBIENTE: development
    container_name: thalamus-acesso-frontend
    restart: unless-stopped
    ports:
      - "8103:80"
    working_dir: /app
    networks:
      - app-network

  thalamus-estrutura-frontend:
    build:
      context: ../workspace/thalamus-estrutura-frontend-vue3
      dockerfile: Dockerfile
      args:
        AMBIENTE: development
    container_name: thalamus-estrutura-frontend
    restart: unless-stopped
    ports:
      - "8104:80"
    working_dir: /app
    networks:
      - app-network

  thalamus-projeto-frontend:
    build:
      context: ../workspace/thalamus-projeto-frontend-vue3
      dockerfile: Dockerfile
      args:
        AMBIENTE: development
    container_name: thalamus-projeto-frontend
    restart: unless-stopped
    ports:
      - "8105:80"
    working_dir: /app
    networks:
      - app-network

  thalamus-orcamento-frontend:
    build:
      context: ../workspace/thalamus-orcamento-frontend-vue3
      dockerfile: Dockerfile
      args:
        AMBIENTE: development
    container_name: thalamus-orcamento-frontend
    restart: unless-stopped
    ports:
      - "8106:80"
    working_dir: /app
    networks:
      - app-network

  thalamus-prototipos:
    image: nginx:alpine
    container_name: thalamus-prototipos
    restart: unless-stopped
    tty: true
    ports:
      - "8108:80"
    volumes:
      - ../workspace/thalamus-prototipos/:/usr/share/nginx/html/
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: thalamus-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      #- ./config/nginx/:/etc/nginx/conf.d/
      - ./config/nginx/sites-enabled:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:8-debian
    container_name: thalamus-db
    restart: unless-stopped
    tty: true
    ports:
      - "3386:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./config/mysql/dbdata:/var/lib/mysql/
      #- ./config/mysql/conf/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
    container_name: roboflex-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8111:80
    networks:
      - app-network
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
    links:
      - db

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: thalamus-jenkins
    restart: on-failure
    tty: true
    ports:
      - "8112:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=https://thalamus.com.br
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    networks:
      - app-network

#Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local